### ISSUE TITLE
Feature: Game Schedule Container

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/ballzandbooze#1]
## Feature Description
Add a container to house rendered Game Schedule data from API

## Format
- Content displayed in ROWS
- ROW: Team Matchup with corresponding team logos (HOME vs VISITORS), and game status (LIVE, FINISHED, NOT STARTED)
- Generate ROW for each matchup on the selected date
 
## Expected behavior
- on page load, container displays the current date's games and information
- on setting a new date parameter using the date picker, that date is used to render new data in container (while clearing out old content)

**Comment by taystarr** [comment]
added bulma attributes to JS file to clean up containers holding teams to make the page more presentable and clean.
