### ISSUE TITLE
Feature: Bar/Brewery Container

### ISSUE THREAD

**Issue by blindsweatyhansolo** [blindsweatyhansolo/ballzandbooze#3]
## Feature Description
- Add a container to house rendered Bar/Brewery data from API
- Allow user to save a bar to their 'favorites'

## Format
- Content displayed in ROWS
- ROW: Brewery Name, Address and Website URL, icon to save bar to localStorage
 
## Expected behavior
- Only display bars that are **currently open for business**,  EXCLUDE bars that fall under categories: _nano_ / _planning_ / _contract_ / _closed_ 
- clicking on the save icon (star?) will change its state to **ACTIVE** and save that bar's data to localStorage
- clicking on an **ACTIVE** save icon will remove that bar's data from localStorage, and change state back to default **PASSIVE**
- on page load, container displays any saved bars at top
- on setting a new area search, clear old content from container EXCEPT for saved bars, render new rows of content

**Comment by blindsweatyhansolo** [comment]
Taylor -- created and styled container for bar search content that is rendered into container when a valid city is searched for

**Comment by blindsweatyhansolo** [comment]
Added modal for when no bars are found within search

**Comment by taystarr** [comment]
Created function for saving favorited bars to local storage and new divs to store favorited bars to load upon refresh, also created skeleton function for removing bars from favorites.

**Comment by blindsweatyhansolo** [comment]
Updated function to save favorited bars to localstorage to get around some issues with removing data from localstorage. Clicking on the footer element marked _Favorite_ will save the targeted bar's name and address and overwrite any existing data in localstorage, allowing for only one bar to be favorited. Function to render bars updated to accommodate changes. Successfully renders saved bar card on refresh, and will remove card and localstorage data when clicking the _Remove Favorite_ footer element
